spring:
  application:
    name: spring-batch

  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: root

  batch:
    job:
      names: ${job.name:NONE}
      #enabled: false
    jdbc:
      initialize-schema: never

